In [4]:
import numpy as np

In [3]:
i = [1,2,3]
j = [5,5,5]
i + j

[1, 2, 3, 5, 5, 5]

In [4]:
x = np.array([1,2,3])
y = np.array([5,5,5])
x + y

array([6, 7, 8])

In [7]:
print(type(x))
print(type(i))

<class 'numpy.ndarray'>
<class 'list'>


In [8]:
x + 5

array([6, 7, 8])

In [14]:
M = np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
print(type(M))

<class 'numpy.ndarray'>


In [16]:
N = np.ones((3,3,3))
print(N)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [19]:
M + i

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [25]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [26]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [32]:
print(a.shape)
print(b.shape)

(3,)
(3, 1)


In [14]:
x = np.arange(9).reshape(3,3)
print(x)
print(x.mean(0))
XMean = x.mean(0)
X_Centered = x- XMean
print(X_Centered)
X_Centered.mean(0)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[3. 4. 5.]
[[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]


array([0., 0., 0.])