In [47]:
#If two balanced dice are rolled, what is the probability that the sum of the two numbers that appear will be odd?
import numpy as np

dice1 = np.array([1,2,3,4,5,6])
dice2 = np.array([1,2,3,4,5,6])[:, np.newaxis]
print(dice1)
print(dice2)
sum_of_dice = dice1 + dice2
print(sum_of_dice)
odd_only = sum_of_dice[sum_of_dice % 2 == 1]
x = np.lcm.reduce([odd_only.size, sum_of_dice.size])
print(x)
print("Probability:{} / {}".format(odd_only.size, sum_of_dice.size))

[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]
 [ 6  7  8  9 10 11]
 [ 7  8  9 10 11 12]]
36
Probability:18 / 36


In [57]:
#If two balanced dice are rolled, what is the probability that the difference between the two numbers that appear will be less than 3?
dice1 = np.array([1,2,3,4,5,6])
dice2 = np.array([1,2,3,4,5,6])
combination = zip(dice1, dice2)
print(type(combination))
for item in combination:
    print(item)
diff_of_dice = dice1 - dice2
print(diff_of_dice)
less_than_three = diff_of_dice[diff_of_dice < 3]
print(less_than_three)
print(less_than_three.size)
x = np.lcm.reduce([less_than_three.size, diff_of_dice.size])
print(x)
print("Probability:{num} / {den}".format(num=less_than_three.size, den=diff_of_dice.size))

<class 'zip'>
(1, 1)
(2, 2)
(3, 3)
(4, 4)
(5, 5)
(6, 6)
[0 0 0 0 0 0]
[0 0 0 0 0 0]
6
6
Probability:6 / 6
