In [47]:
#If two balanced dice are rolled, what is the probability that the sum of the two numbers that appear will be odd?
import numpy as np

dice1 = np.array([1,2,3,4,5,6])
dice2 = np.array([1,2,3,4,5,6])[:, np.newaxis]
print(dice1)
print(dice2)
sum_of_dice = dice1 + dice2
print(sum_of_dice)
odd_only = sum_of_dice[sum_of_dice % 2 == 1]
x = np.lcm.reduce([odd_only.size, sum_of_dice.size])
print(x)
print("Probability:{} / {}".format(odd_only.size, sum_of_dice.size))

[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]
 [ 6  7  8  9 10 11]
 [ 7  8  9 10 11 12]]
36
Probability:18 / 36


In [18]:
#If two balanced dice are rolled, what is the probability that the difference between the two numbers that appear will be less than 3?
import numpy as np

dice1 = np.array([1,2,3,4,5,6])
dice2 = np.array([1,2,3,4,5,6])[:, np.newaxis]
diff_of_dice = np.abs(dice1 - dice2)
print(diff_of_dice)
less_than_three = diff_of_dice[diff_of_dice < 3]
print(less_than_three)
print(less_than_three.size)
x = np.lcm.reduce([less_than_three.size, diff_of_dice.size])
print(x)
print("Probability:{num} / {den}".format(num=less_than_three.size, den=diff_of_dice.size))

[[0 1 2 3 4 5]
 [1 0 1 2 3 4]
 [2 1 0 1 2 3]
 [3 2 1 0 1 2]
 [4 3 2 1 0 1]
 [5 4 3 2 1 0]]
[0 1 2 1 0 1 2 2 1 0 1 2 2 1 0 1 2 2 1 0 1 2 1 0]
24
72
Probability:24 / 36


In [22]:
x = [1,2,3,-1]
result = map(abs, x)
print(list(result))

[1, 2, 3, 1]


In [23]:
#A school contains students in grades 1, 2, 3, 4, 5, and 6. Grades 2, 3, 4, 5, and 6 all contain the same number of students, 
#but there are twice this number in grade 1. If a
#student is selected at random from a list of all the students
#in the school, what is the probability that she will be in
#grade 3?

students = [1,1,2,3,4,5,6]
for i in range(1, 10):
    print(i)


1
2
3
4
5
6
7
8
9


In [24]:
x = 'A'
if x == 'A':
    print(x)

A
