# This is basic numpy arrays

In [1]:
import numpy as np

## Create a 2x2 matrix manually

In [17]:
arr1 = np.array([[1,2], [3,4]])
print('Array:', arr1)
print('Shape:', arr1.shape)
print('Dimension:', arr1.ndim)
print('Number of Elements in the array:', arr1.size)

Array: [[1 2]
 [3 4]]
Shape: (2, 2)
Dimension: 2
Number of Elements in the array: 4


## Create a 2x2 matrix using np.arange

In [18]:
arr2 = np.arange(4).reshape(2,2)
print('Array:', arr2)
print('Shape:', arr2.shape)
print('Dimension:', arr2.ndim)
print('Number of Elements in the array:', arr2.size)

Array: [[0 1]
 [2 3]]
Shape: (2, 2)
Dimension: 2
Number of Elements in the array: 4


## Create a 2x2 matrix with default zeros

In [23]:
arr3 = np.zeros(shape=(2,2))
print('Array:', arr3)
print('Shape:', arr3.shape)
print('Dimension:', arr3.ndim)
print('Number of Elements in the array:', arr3.size)

Array: [[0. 0.]
 [0. 0.]]
Shape: (2, 2)
Dimension: 2
Number of Elements in the array: 4


## Create a 2x2 matrix with default ones

In [24]:
arr4 = np.ones(shape=(2,2))
print('Array:', arr4)
print('Shape:', arr4.shape)
print('Dimension:', arr4.ndim)
print('Number of Elements in the array:', arr4.size)

Array: [[1. 1.]
 [1. 1.]]
Shape: (2, 2)
Dimension: 2
Number of Elements in the array: 4


## Basic Operations

In [30]:
print('Original Array:', arr)
print('Add 2', arr1 + 2)
print('Subtract 2', arr1 - 2)
print('Multiply by 2', arr1 * 2)
print('Divide by 2', arr1 / 2)

Original Array: [[0 1]
 [2 3]]
Add 2 [[3 4]
 [5 6]]
Subtract 2 [[-1  0]
 [ 1  2]]
Multiply by 2 [[2 4]
 [6 8]]
Divide by 2 [[0.5 1. ]
 [1.5 2. ]]


## Matrix Operation

In [35]:
print('Array 1:\n', arr1)
print('Array 2:\n', arr2)
print('Dot Matrix(@)\n', arr1 @ arr2)
print('Dot Matrix(dot)\n', arr1.dot(arr2))

Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[0 1]
 [2 3]]
Dot Matrix(@)
 [[ 4  7]
 [ 8 15]]
Dot Matrix(dot)
 [[ 4  7]
 [ 8 15]]


## Sum, Min, Max

In [38]:
print('Array 1:', arr1)
print('Sum:', arr1.sum())
print('Sum:', arr1.min())
print('Sum:', arr1.max())

Array 1: [[1 2]
 [3 4]]
Sum: 10
Sum: 1
Sum: 4


## Sum, Min, Max per column

In [41]:
print('Array 1:', arr1)
print('Sum:', arr1.sum(axis=0))
print('Sum:', arr1.min(axis=0))
print('Sum:', arr1.max(axis=0))

Array 1: [[1 2]
 [3 4]]
Sum: [4 6]
Sum: [1 2]
Sum: [3 4]


## Sum, Min, Max per row

In [43]:
print('Array 1:', arr1)
print('Sum:', arr1.sum(axis=1))
print('Sum:', arr1.min(axis=1))
print('Sum:', arr1.max(axis=1))

Array 1: [[1 2]
 [3 4]]
Sum: [3 7]
Sum: [1 3]
Sum: [2 4]
